# Generated by Django 2.0 on 2018-01-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=100)),
                ('bname', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=100)),
                ('press', models.CharField(max_length=200)),
                ('pretime', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=200)),
                ('prise', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
            ],
        ),
    ]
