# Generated by Django 2.0 on 2018-01-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbook',
            name='ISBN',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dbook',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dbook',
            name='bname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dbook',
            name='number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dbook',
            name='press',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dbook',
            name='pretime',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dbook',
            name='prise',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dbook',
            name='rate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dbook',
            name='score',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
