# Generated by Django 2.0 on 2018-01-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180104_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='jmubook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('publisher_city', models.CharField(max_length=100, null=True)),
                ('publisher', models.CharField(max_length=100, null=True)),
                ('publish_year', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('isbn', models.CharField(max_length=100, null=True)),
                ('titles', models.CharField(max_length=200, null=True)),
                ('authors', models.CharField(max_length=100, null=True)),
                ('tags', models.CharField(max_length=100, null=True)),
                ('associations', models.CharField(max_length=100, null=True)),
                ('total', models.CharField(max_length=100, null=True)),
                ('loan', models.CharField(max_length=100, null=True)),
                ('available', models.CharField(max_length=100, null=True)),
                ('frequence', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
